// ==========================================================
// คลังคำศัพท์ English A1
// ==========================================================
window.flashVocabDataEnA1 = [
{ word:"a, an", meaning:"คำนำหน้านาม, ไม่ชี้เฉพาะ" },
{ word:"about", meaning:"เกี่ยวกับ, ประมาณ" },
{ word:"above", meaning:"เหนือ, ข้างบน" },
{ word:"across", meaning:"ข้าม, อีกฝั่ง" },
{ word:"action", meaning:"การกระทำ, การต่อสู้" },
{ word:"activity", meaning:"กิจกรรม" },
{ word:"actor", meaning:"นักแสดงชาย" },
{ word:"actress", meaning:"นักแสดงหญิง" },
{ word:"add", meaning:"เพิ่ม, บวก" },
{ word:"address", meaning:"ที่อยู่" },
{ word:"adult", meaning:"ผู้ใหญ่" },
{ word:"advice", meaning:"คำแนะนำ" },
{ word:"afraid", meaning:"กลัว" },
{ word:"after", meaning:"หลังจาก, ภายหลัง" },
{ word:"afternoon", meaning:"ตอนบ่าย" },
{ word:"again", meaning:"อีกครั้ง" },
{ word:"age", meaning:"อายุ, ยุคสมัย" },
{ word:"ago", meaning:"มาแล้ว, ล่วงมาแล้ว" },
{ word:"agree", meaning:"เห็นด้วย, ตกลง" },
{ word:"air", meaning:"อากาศ" },
{ word:"airport", meaning:"สนามบิน" },
{ word:"all", meaning:"ทั้งหมด, ทุกคน" },
{ word:"also", meaning:"ด้วย, เช่นกัน" },
{ word:"always", meaning:"เสมอ, เป็นประจำ" },
{ word:"amazing", meaning:"น่าทึ่ง, น่าประหลาดใจ" },
{ word:"and", meaning:"และ" },
{ word:"angry", meaning:"โกรธ" },
{ word:"animal", meaning:"สัตว์" },
{ word:"another", meaning:"อีกหนึ่ง, อื่น" },
{ word:"answer", meaning:"ตอบ, คำตอบ" },
{ word:"any", meaning:"บ้าง, ใดๆ" },
{ word:"anyone", meaning:"ใครก็ตาม, ใครไหม" },
{ word:"anything", meaning:"สิ่งใด, อะไรก็ตาม" },
{ word:"apartment", meaning:"ห้องชุด, แฟลต" },
{ word:"apple", meaning:"แอปเปิ้ล" },
{ word:"April", meaning:"เมษายน" },
{ word:"area", meaning:"พื้นที่, บริเวณ" },
{ word:"arm", meaning:"แขน" },
{ word:"around", meaning:"รอบๆ, ประมาณ" },
{ word:"arrive", meaning:"มาถึง" },
{ word:"art", meaning:"ศิลปะ" },
{ word:"article", meaning:"บทความ, สิ่งของ" },
{ word:"artist", meaning:"ศิลปิน" },
{ word:"as", meaning:"ตามที่, ในฐานะ" },
{ word:"ask", meaning:"ถาม, ขอร้อง" },
{ word:"at", meaning:"ที่, เวลา" },
{ word:"August", meaning:"สิงหาคม" },
{ word:"aunt", meaning:"ป้า, น้า, อาหญิง" },
{ word:"autumn", meaning:"ฤดูใบไม้ร่วง" },
{ word:"away", meaning:"ไปไกล, ห่างออกไป" },
{ word:"baby", meaning:"ทารก" },
{ word:"back", meaning:"หลัง, กลับมา" },
{ word:"bad", meaning:"เลว, แย่" },
{ word:"bag", meaning:"กระเป๋า, ถุง" },
{ word:"ball", meaning:"ลูกบอล" },
{ word:"banana", meaning:"กล้วย" },
{ word:"band", meaning:"วงดนตรี, แถบ" },
{ word:"bank (money)", meaning:"ธนาคาร" },
{ word:"bath", meaning:"การอาบน้ำ, อ่างอาบน้ำ" },
{ word:"bathroom", meaning:"ห้องน้ำ" },
{ word:"be", meaning:"เป็น, อยู่, คือ" },
{ word:"beach", meaning:"ชายหาด" },
{ word:"beautiful", meaning:"สวย, งดงาม" },
{ word:"because", meaning:"เพราะว่า" },
{ word:"become", meaning:"กลายเป็น" },
{ word:"bed", meaning:"เตียงนอน" },
{ word:"bedroom", meaning:"ห้องนอน" },
{ word:"beer", meaning:"เบียร์" },
{ word:"before", meaning:"ก่อน, ข้างหน้า" },
{ word:"begin", meaning:"เริ่ม, เริ่มต้น" },
{ word:"beginning", meaning:"จุดเริ่มต้น" },
{ word:"behind", meaning:"ข้างหลัง, ข้างท้าย" },
{ word:"believe", meaning:"เชื่อ, เลื่อมใส" },
{ word:"below", meaning:"ข้างล่าง, ต่ำกว่า" },
{ word:"best", meaning:"ดีที่สุด" },
{ word:"better", meaning:"ดีกว่า" },
{ word:"between", meaning:"ระหว่าง" },
{ word:"bicycle", meaning:"จักรยาน" },
{ word:"big", meaning:"ใหญ่" },
{ word:"bike", meaning:"จักรยาน, มอเตอร์ไซค์" },
{ word:"bill", meaning:"ใบเสร็จ, ร่างกฎหมาย" },
{ word:"bird", meaning:"นก" },
{ word:"birthday", meaning:"วันเกิด" },
{ word:"black", meaning:"สีดำ" },
{ word:"blog", meaning:"บล็อก, เว็บไซค์ส่วนตัว" },
{ word:"blonde", meaning:"ผมบลอนด์, สีทอง" },
{ word:"blue", meaning:"สีน้ำเงิน, สีฟ้า" },
{ word:"boat", meaning:"เรือ" },
{ word:"body", meaning:"ร่างกาย, ลำตัว" },
{ word:"book", meaning:"หนังสือ, จอง" },
{ word:"boot", meaning:"รองเท้าบูท, ท้ายรถ" },
{ word:"bored", meaning:"เบื่อ" },
{ word:"boring", meaning:"น่าเบื่อ" },
{ word:"born", meaning:"เกิด" },
{ word:"both", meaning:"ทั้งสอง" },
{ word:"bottle", meaning:"ขวด" },
{ word:"box", meaning:"กล่อง" },
{ word:"boy", meaning:"เด็กชาย" },
{ word:"boyfriend", meaning:"แฟนหนุ่ม" },
{ word:"bread", meaning:"ขนมปัง" },
{ word:"break", meaning:"แตก, หัก, พัก" },
{ word:"breakfast", meaning:"อาหารเช้า" },
{ word:"bring", meaning:"นำมา, พามา" },
{ word:"brother", meaning:"พี่ชาย, น้องชาย" },
{ word:"brown", meaning:"สีน้ำตาล" },
{ word:"build", meaning:"สร้าง" },
{ word:"building", meaning:"ตึก, อาคาร" },
{ word:"Buffet", meaning:"บัฟเฟ่ต์" },
{ word:"bus", meaning:"รถเมล์, รถบัส" },
{ word:"business", meaning:"ธุรกิจ" },
{ word:"busy", meaning:"ยุ่ง, ไม่ว่าง" },
{ word:"but", meaning:"แต่" },
{ word:"butter", meaning:"เนย" },
{ word:"buy", meaning:"ซื้อ" },
{ word:"by", meaning:"โดย, ข้างๆ" },
{ word:"bye", meaning:"ลาก่อน" },
{ word:"cafe", meaning:"คาเฟ่, ร้านกาแฟ" },
{ word:"cake", meaning:"เค้ก" },
{ word:"call", meaning:"โทร, เรียก" },
{ word:"camera", meaning:"กล้องถ่ายรูป" },
{ word:"can1", meaning:"สามารถ, กระป๋อง" },
{ word:"cannot", meaning:"ไม่สามารถ" },
{ word:"capital", meaning:"เมืองหลวง, เงินทุน" },
{ word:"car", meaning:"รถยนต์" },
{ word:"card", meaning:"บัตร, การ์ด" },
{ word:"career", meaning:"อาชีพ" },
{ word:"carrot", meaning:"แครอท" },
{ word:"carry", meaning:"ถือ, แบก, หิ้ว" },
{ word:"cat", meaning:"แมว" },
{ word:"CD", meaning:"ซีดี" },
{ word:"cent", meaning:"เซนต์" },
{ word:"centre", meaning:"ศูนย์กลาง" },
{ word:"century", meaning:"ศตวรรษ" },
{ word:"chair", meaning:"เก้าอี้" },
{ word:"change", meaning:"เปลี่ยน, เงินทอน" },
{ word:"chart", meaning:"แผนภูมิ, ตาราง" },
{ word:"cheap", meaning:"ถูก, ราคาถูก" },
{ word:"check", meaning:"ตรวจสอบ" },
{ word:"cheese", meaning:"ชีส, เนยแข็ง" },
{ word:"chicken", meaning:"ไก่, เนื้อไก่" },
{ word:"child", meaning:"เด็ก" },
{ word:"chocolate", meaning:"ช็อกโกแลต" },
{ word:"choose", meaning:"เลือก" },
{ word:"cinema", meaning:"โรงภาพยนตร์" },
{ word:"city", meaning:"เมือง, นคร" },
{ word:"class", meaning:"ชั้นเรียน, ประเภท" },
{ word:"classroom", meaning:"ห้องเรียน" },
{ word:"clean", meaning:"สะอาด, ทำความสะอาด" },
{ word:"climb", meaning:"ปีน, ไต่" },
{ word:"clock", meaning:"นาฬิกาตั้งโต๊ะ" },
{ word:"close1", meaning:"ปิด, ใกล้ชิด" },
{ word:"clothes", meaning:"เสื้อผ้า" },
{ word:"club", meaning:"สโมสร, คลับ" },
{ word:"coat", meaning:"เสื้อโค้ต, เสื้อนอก" },
{ word:"coffee", meaning:"กาแฟ" },
{ word:"cold", meaning:"หนาว, เย็น, เป็นหวัด" },
{ word:"college", meaning:"วิทยาลัย" },
{ word:"colour", meaning:"สี" },
{ word:"come", meaning:"มา" },
{ word:"common", meaning:"ร่วมกัน, ธรรมดา" },
{ word:"company", meaning:"บริษัท, เพื่อนร่วมทาง" },
{ word:"compare", meaning:"เปรียบเทียบ" },
{ word:"complete", meaning:"สมบูรณ์, ทำเสร็จ" },
{ word:"computer", meaning:"คอมพิวเตอร์" },
{ word:"concert", meaning:"คอนเสิร์ต" },
{ word:"conversation", meaning:"การสนทนา" },
{ word:"cook", meaning:"ทำอาหาร, คนครัว" },
{ word:"cooking", meaning:"การทำอาหาร" },
{ word:"cool", meaning:"เย็นสบาย, เจ๋ง" },
{ word:"correct", meaning:"ถูกต้อง, แก้ไข" },
{ word:"cost", meaning:"ราคา, มีราคา" },
{ word:"could", meaning:"สามารถ" },
{ word:"country", meaning:"ประเทศ, ชนบท" },
{ word:"course", meaning:"หลักสูตร, รายวิชา" },
{ word:"cousin", meaning:"ลูกพี่ลูกน้อง" },
{ word:"cow", meaning:"วัวตัวเมีย" },
{ word:"cream", meaning:"ครีม" },
{ word:"create", meaning:"สร้าง, สร้างสรรค์" },
{ word:"culture", meaning:"วัฒนธรรม" },
{ word:"cup", meaning:"ถ้วย, ถ้วยรางวัล" },
{ word:"customer", meaning:"ลูกค้า" },
{ word:"cut", meaning:"ตัด, หั่น" },
{ word:"dad", meaning:"พ่อ" },
{ word:"dance", meaning:"เต้นรำ" },
{ word:"dancer", meaning:"นักเต้น" },
{ word:"dancing", meaning:"การเต้นรำ" },
{ word:"dangerous", meaning:"อันตราย" },
{ word:"dark", meaning:"มืด, สีเข้ม" },
{ word:"date", meaning:"วันที่, นัดพบ" },
{ word:"daughter", meaning:"ลูกสาว" },
{ word:"day", meaning:"วัน, กลางวัน" },
{ word:"dear", meaning:"ที่รัก, แพง" },
{ word:"December", meaning:"ธันวาคม" },
{ word:"decide", meaning:"ตัดสินใจ" },
{ word:"delicious", meaning:"อร่อย" },
{ word:"describe", meaning:"อธิบาย, บรรยาย" },
{ word:"description", meaning:"การอธิบาย" },
{ word:"design", meaning:"ออกแบบ" },
{ word:"desk", meaning:"โต๊ะทำงาน" },
{ word:"detail", meaning:"รายละเอียด" },
{ word:"dialogue", meaning:"บทสนทนา" },
{ word:"dictionary", meaning:"พจนานุกรม" },
{ word:"die", meaning:"ตาย" },
{ word:"diet", meaning:"อาหาร, ควบคุมอาหาร" },
{ word:"difference", meaning:"ความแตกต่าง" },
{ word:"different", meaning:"แตกต่าง" },
{ word:"difficult", meaning:"ยาก" },
{ word:"dinner", meaning:"อาหารเย็น" },
{ word:"dirty", meaning:"สกปรก" },
{ word:"discuss", meaning:"สนทนา, ถกเถียง" },
{ word:"dish", meaning:"จาน, อาหารจานเด็ด" },
{ word:"do1", meaning:"ทำ" },
{ word:"doctor", meaning:"หมอ, แพทย์" },
{ word:"dog", meaning:"สุนัข" },
{ word:"dollar", meaning:"ดอลลาร์" },
{ word:"door", meaning:"ประตู" },
{ word:"down", meaning:"ลง, ข้างล่าง" },
{ word:"downstairs", meaning:"ชั้นล่าง" },
{ word:"draw", meaning:"วาด, ลาก, เสมอ" },
{ word:"dress", meaning:"ชุดกระโปรง, แต่งตัว" },
{ word:"drink", meaning:"ดื่ม, เครื่องดื่ม" },
{ word:"drive", meaning:"ขับรถ" },
{ word:"driver", meaning:"คนขับรถ" },
{ word:"during", meaning:"ระหว่าง, ในช่วงเวลา" },
{ word:"DVD", meaning:"ดีวีดี" },
{ word:"each", meaning:"แต่ละ" },
{ word:"ear", meaning:"หู" },
{ word:"early", meaning:"แต่เช้า, ก่อนเวลา" },
{ word:"east", meaning:"ทิศตะวันออก" },
{ word:"easy", meaning:"ง่าย" },
{ word:"eat", meaning:"กิน" },
{ word:"egg", meaning:"ไข่" },
{ word:"eight", meaning:"แปด" },
{ word:"eighteen", meaning:"สิบแปด" },
{ word:"eighty", meaning:"แปดสิบ" },
{ word:"elephant", meaning:"ช้าง" },
{ word:"eleven", meaning:"สิบเอ็ด" },
{ word:"else", meaning:"อื่น, นอกจากนี้" },
{ word:"email", meaning:"อีเมล" },
{ word:"end", meaning:"จบ, ตอนจบ" },
{ word:"enjoy", meaning:"สนุกสนาน, เพลิดเพลิน" },
{ word:"enough", meaning:"พอ, เพียงพอ" },
{ word:"euro", meaning:"ยูโร" },
{ word:"even", meaning:"แม้แต่, เท่ากัน" },
{ word:"evening", meaning:"ตอนเย็น" },
{ word:"event", meaning:"เหตุการณ์, งานกิจกรรม" },
{ word:"ever", meaning:"เคย, ตลอดไป" },
{ word:"every", meaning:"ทุกๆ" },
{ word:"everybody", meaning:"ทุกคน" },
{ word:"everyone", meaning:"ทุกคน" },
{ word:"everything", meaning:"ทุกสิ่งทุกอย่าง" },
{ word:"exam", meaning:"การสอบ" },
{ word:"example", meaning:"ตัวอย่าง" },
{ word:"excited", meaning:"ตื่นเต้น" },
{ word:"exciting", meaning:"น่าตื่นเต้น" },
{ word:"exercise", meaning:"ออกกำลังกาย, แบบฝึกหัด" },
{ word:"expensive", meaning:"แพง" },
{ word:"explain", meaning:"อธิบาย" },
{ word:"extra", meaning:"พิเศษ, เพิ่มเติม" },
{ word:"eye", meaning:"ตา" },
{ word:"face", meaning:"ใบหน้า, เผชิญหน้า" },
{ word:"fact", meaning:"ข้อเท็จจริง" },
{ word:"fall", meaning:"ตก, ร่วง, ฤดูใบไม้ร่วง" },
{ word:"false", meaning:"ผิด, ปลอม" },
{ word:"family", meaning:"ครอบครัว" },
{ word:"famous", meaning:"มีชื่อเสียง" },
{ word:"fantastic", meaning:"มหัศจรรนด์, เยี่ยมยอด" },
{ word:"far", meaning:"ไกล" },
{ word:"farm", meaning:"ฟาร์ม, ไร่ระเบียง" },
{ word:"farmer", meaning:"ชาวนา, เกษตรกร" },
{ word:"fast", meaning:"เร็ว" },
{ word:"fat", meaning:"อ้วน, ไขมัน" },
{ word:"father", meaning:"พ่อ" },
{ word:"favourite", meaning:"โปรดปราน, ชื่นชอบ" },
{ word:"February", meaning:"กุมภาพันธ์" },
{ word:"feel", meaning:"รู้สึก" },
{ word:"feeling", meaning:"ความรู้สึก" },
{ word:"festival", meaning:"เทศกาล" },
{ word:"few", meaning:"น้อย, สองสามคน" },
{ word:"fifteen", meaning:"สิบห้า" },
{ word:"fifth", meaning:"ที่ห้า, ลำดับที่ห้า" },
{ word:"fifty", meaning:"ห้าสิบ" },
{ word:"fill", meaning:"เติมให้เต็ม" },
{ word:"film", meaning:"ภาพยนตร์, ฟิล์ม" },
{ word:"final", meaning:"สุดท้าย, รอบชิง" },
{ word:"find", meaning:"หา, พบ" },
{ word:"fine", meaning:"ดี, สบายดี, ค่าปรับ" },
{ word:"finish", meaning:"เสร็จ, จบ" },
{ word:"fire", meaning:"ไฟ, ไล่ออก" },
{ word:"first", meaning:"แรก, อันดับแรก" },
{ word:"fish", meaning:"ปลา" },
{ word:"five", meaning:"ห้า" },
{ word:"flat", meaning:"แบน, ห้องชุด" },
{ word:"flight", meaning:"เที่ยวบิน" },
{ word:"floor", meaning:"พื้น, ชั้น" },
{ word:"flower", meaning:"ดอกไม้" },
{ word:"fly", meaning:"บิน, แมลงวัน" },
{ word:"follow", meaning:"ตาม, ติดตาม" },
{ word:"food", meaning:"อาหาร" },
{ word:"foot", meaning:"เท้า" },
{ word:"football", meaning:"ฟุตบอล" },
{ word:"for", meaning:"สำหรับ, เพื่อ" },
{ word:"forget", meaning:"ลืม" },
{ word:"form", meaning:"รูปแบบ, แบบฟอร์ม" },
{ word:"forty", meaning:"สี่สิบ" },
{ word:"four", meaning:"สี่" },
{ word:"fourteen", meaning:"สิบสี่" },
{ word:"fourth", meaning:"ที่สี่, ลำดับที่สี่" },
{ word:"free", meaning:"ฟรี, ว่าง, อิสระ" },
{ word:"Friday", meaning:"วันศุกร์" },
{ word:"friend", meaning:"เพื่อน" },
{ word:"friendly", meaning:"เป็นมิตร" },
{ word:"from", meaning:"จาก" },
{ word:"front", meaning:"ข้างหน้า, ด้านหน้า" },
{ word:"fruit", meaning:"ผลไม้" },
{ word:"full", meaning:"เต็ม" },
{ word:"fun", meaning:"สนุกสนาน" },
{ word:"funny", meaning:"ตลก" },
{ word:"future", meaning:"อนาคต" },
{ word:"game", meaning:"เกม" },
{ word:"garden", meaning:"สวน" },
{ word:"geography", meaning:"ภูมิศาสตร์" },
{ word:"get", meaning:"ได้รับ, เอา" },
{ word:"girl", meaning:"เด็กหญิง" },
{ word:"girlfriend", meaning:"แฟนสาว" },
{ word:"give", meaning:"ให้" },
{ word:"glass", meaning:"แก้ว, กระจก" },
{ word:"go", meaning:"ไป" },
{ word:"good", meaning:"ดี" },
{ word:"goodbye", meaning:"ลาก่อน" },
{ word:"grandfather", meaning:"ปู่, ตา" },
{ word:"grandmother", meaning:"ย่า, ยาย" },
{ word:"grandparent", meaning:"ปู่ย่าตายาย" },
{ word:"great", meaning:"ยอดเยี่ยม, ยิ่งใหญ่" },
{ word:"green", meaning:"สีเขียว" },
{ word:"grey", meaning:"สีเทา" },
{ word:"group", meaning:"กลุ่ม" },
{ word:"grow", meaning:"เติบโต, ปลูก" },
{ word:"guess", meaning:"เดา" },
{ word:"guitar", meaning:"กีตาร์" },
{ word:"gym", meaning:"โรงยิม" },
{ word:"hair", meaning:"ผม, ขน" },
{ word:"half", meaning:"ครึ่ง" },
{ word:"hand", meaning:"มือ" },
{ word:"happen", meaning:"เกิดขึ้น" },
{ word:"happy", meaning:"มีความสุข" },
{ word:"hard", meaning:"ยาก, แข็ง, หนัก" },
{ word:"hat", meaning:"หมวก" },
{ word:"hate", meaning:"เกลียด" },
{ word:"have", meaning:"มี, กิน" },
{ word:"have to", meaning:"ต้อง" },
{ word:"he", meaning:"เขา (ผู้ชาย)" },
{ word:"head", meaning:"หัว, ศีรษะ" },
{ word:"health", meaning:"สุขภาพ" },
{ word:"healthy", meaning:"สุขภาพดี" },
{ word:"hear", meaning:"ได้ยิน" },
{ word:"hello", meaning:"สวัสดี" },
{ word:"help", meaning:"ช่วย, ความช่วยเหลือ" },
{ word:"her", meaning:"เธอ, ของเธอ" },
{ word:"here", meaning:"ที่นี่" },
{ word:"hey", meaning:"เฮ้" },
{ word:"hi", meaning:"สวัสดี" },
{ word:"high", meaning:"สูง" },
{ word:"him", meaning:"เขา (ผู้ชาย, กรรม)" },
{ word:"his", meaning:"ของเขา" },
{ word:"history", meaning:"ประวัติศาสตร์" },
{ word:"hobby", meaning:"งานอดิเรก" },
{ word:"holiday", meaning:"วันหยุด" },
{ word:"home", meaning:"บ้าน" },
{ word:"homework", meaning:"การบ้าน" },
{ word:"hope", meaning:"หวัง, ความหวัง" },
{ word:"horse", meaning:"ม้า" },
{ word:"hospital", meaning:"โรงพยาบาล" },
{ word:"hot", meaning:"ร้อน, เผ็ด" },
{ word:"hotel", meaning:"โรงแรม" },
{ word:"hour", meaning:"ชั่วโมง" },
{ word:"house", meaning:"บ้าน" },
{ word:"how", meaning:"อย่างไร" },
{ word:"however", meaning:"อย่างไรก็ตาม" },
{ word:"hundred", meaning:"ร้อย" },
{ word:"hungry", meaning:"หิว" },
{ word:"husband", meaning:"สามี" },
{ word:"I", meaning:"ฉัน, ผม" },
{ word:"ice", meaning:"น้ำแข็ง" },
{ word:"ice cream", meaning:"ไอศกรีม" },
{ word:"idea", meaning:"ความคิด" },
{ word:"if", meaning:"ถ้า" },
{ word:"imagine", meaning:"จินตนาการ" },
{ word:"important", meaning:"สำคัญ" },
{ word:"improve", meaning:"ปรับปรุง, พัฒนา" },
{ word:"in", meaning:"ใน" },
{ word:"include", meaning:"รวมถึง" },
{ word:"information", meaning:"ข้อมูล" },
{ word:"interest", meaning:"ความสนใจ, ดอกเบี้ย" },
{ word:"interested", meaning:"รู้สึกสนใจ" },
{ word:"interesting", meaning:"น่าสนใจ" },
{ word:"internet", meaning:"อินเทอร์เน็ต" },
{ word:"interview", meaning:"สัมภาษณ์" },
{ word:"into", meaning:"เข้าไปใน" },
{ word:"introduce", meaning:"แนะนำให้รู้จัก" },
{ word:"island", meaning:"เกาะ" },
{ word:"it", meaning:"มัน" },
{ word:"its", meaning:"ของมัน" },
{ word:"jacket", meaning:"เสื้อแจ็คเก็ต" },
{ word:"January", meaning:"มกราคม" },
{ word:"jeans", meaning:"กางเกงยีนส์" },
{ word:"job", meaning:"งาน, อาชีพ" },
{ word:"join", meaning:"เข้าร่วม" },
{ word:"journey", meaning:"การเดินทาง" },
{ word:"juice", meaning:"น้ำผลไม้" },
{ word:"July", meaning:"กรกฎาคม" },
{ word:"June", meaning:"มิถุนายน" },
{ word:"just", meaning:"เพิ่งจะ, แค่" },
{ word:"keep", meaning:"เก็บรักษา" },
{ word:"key", meaning:"กุญแจ, สำคัญ" },
{ word:"kilometre", meaning:"กิโลเมตร" },
{ word:"kind (type)", meaning:"ชนิด, ประเภท" },
{ word:"kitchen", meaning:"ห้องครัว" },
{ word:"know", meaning:"รู้, รู้จัก" },
{ word:"land", meaning:"ที่ดิน, พื้นดิน" },
{ word:"language", meaning:"ภาษา" },
{ word:"large", meaning:"ใหญ่" },
{ word:"last1 (final)", meaning:"สุดท้าย, ล่าสุด" },
{ word:"late", meaning:"สาย, ดึก" },
{ word:"later", meaning:"ภายหลัง, ต่อมา" },
{ word:"laugh", meaning:"หัวเราะ" },
{ word:"learn", meaning:"เรียน, เรียนรู้" },
{ word:"leave", meaning:"ออกจาก, ทิ้งไว้" },
{ word:"left", meaning:"ซ้าย, ที่เหลืออยู่" },
{ word:"leg", meaning:"ขา" },
{ word:"lesson", meaning:"บทเรียน" },
{ word:"let", meaning:"ปล่อย, ยอมให้" },
{ word:"letter", meaning:"จดหมาย, ตัวอักษร" },
{ word:"library", meaning:"ห้องสมุด" },
{ word:"lie1", meaning:"โกหก, นอนราบ" },
{ word:"life", meaning:"ชีวิต" },
{ word:"light (from the sun/a lamp)", meaning:"แสงไฟ, แสงแดด" },
{ word:"adj.", meaning:"เบา, สีอ่อน" },
{ word:"like (similar)", meaning:"เหมือน, คล้าย" },
{ word:"like (find sb/sth pleasant)", meaning:"ชอบ" },
{ word:"line", meaning:"เส้น, แถว" },
{ word:"lion", meaning:"สิงโต" },
{ word:"list", meaning:"รายการ, รายชื่อ" },
{ word:"listen", meaning:"ฟัง" },
{ word:"little", meaning:"เล็กน้อย, ตัวเล็ก" },
{ word:"live1", meaning:"อาศัยอยู่, มีชีวิต" },
{ word:"local", meaning:"ท้องถิ่น" },
{ word:"long1", meaning:"ยาว, นาน" },
{ word:"look", meaning:"มองดู" },
{ word:"lose", meaning:"ทำหาย, แพ้" },
{ word:"lot", meaning:"จำนวนมาก" },
{ word:"love", meaning:"รัก, ความรัก" },
{ word:"lunch", meaning:"อาหารกลางวัน" },
{ word:"machine", meaning:"เครื่องจักร" },
{ word:"magazine", meaning:"นิตยสาร" },
{ word:"main", meaning:"หลัก, สำคัญที่สุด" },
{ word:"make", meaning:"ทำ, ผลิต" },
{ word:"man", meaning:"ผู้ชาย" },
{ word:"many", meaning:"มาก, หลาย" },
{ word:"map", meaning:"แผนที่" },
{ word:"March", meaning:"มีนาคม" },
{ word:"market", meaning:"ตลาด" },
{ word:"married", meaning:"แต่งงานแล้ว" },
{ word:"match (contest/correspond)", meaning:"การแข่งขัน, จับคู่" },
{ word:"May", meaning:"พฤษภาคม" },
{ word:"maybe", meaning:"อาจจะ" },
{ word:"me", meaning:"ฉัน (กรรม)" },
{ word:"meal", meaning:"มื้ออาหาร" },
{ word:"mean", meaning:"หมายความว่า" },
{ word:"meaning", meaning:"ความหมาย" },
{ word:"meat", meaning:"เนื้อสัตว์" },
{ word:"meet", meaning:"พบ, เจอ" },
{ word:"meeting", meaning:"การประชุม" },
{ word:"member", meaning:"สมาชิก" },
{ word:"menu", meaning:"เมนู" },
{ word:"message", meaning:"ข้อความ" },
{ word:"metre", meaning:"เมตร" },
{ word:"midnight", meaning:"เที่ยงคืน" },
{ word:"mile", meaning:"ไมล์" },
{ word:"milk", meaning:"นม" },
{ word:"million", meaning:"ล้าน" },
{ word:"minute1", meaning:"นาที" },
{ word:"miss", meaning:"คิดถึง, พลาด" },
{ word:"mistake", meaning:"ข้อผิดพลาด" },
{ word:"model", meaning:"แบบจำลอง, นางแบบ" },
{ word:"modern", meaning:"ทันสมัย" },
{ word:"moment", meaning:"ชั่วครู่, ขณะนั้น" },
{ word:"Monday", meaning:"วันจันทร์" },
{ word:"money", meaning:"เงิน" },
{ word:"month", meaning:"เดือน" },
{ word:"more", meaning:"มากกว่า, อีก" },
{ word:"morning", meaning:"ตอนเช้า" },
{ word:"most", meaning:"มากที่สุด" },
{ word:"mother", meaning:"แม่" },
{ word:"mountain", meaning:"ภูเขา" },
{ word:"mouse", meaning:"หนู, เมาส์" },
{ word:"mouth", meaning:"ปาก" },
{ word:"move", meaning:"เคลื่อนย้าย" },
{ word:"movie", meaning:"ภาพยนตร์" },
{ word:"much", meaning:"มาก" },
{ word:"mum", meaning:"แม่" },
{ word:"museum", meaning:"พิพิธภัณฑ์" },
{ word:"music", meaning:"ดนตรี, เพลง" },
{ word:"must", meaning:"ต้อง" },
{ word:"my", meaning:"ของฉัน" },
{ word:"name", meaning:"ชื่อ" },
{ word:"natural", meaning:"ธรรมชาติ" },
{ word:"near", meaning:"ใกล้" },
{ word:"need", meaning:"ต้องการ" },
{ word:"negative", meaning:"เชิงลบ, ปฏิเสธ" },
{ word:"neighbour", meaning:"เพื่อนบ้าน" },
{ word:"never", meaning:"ไม่เคย" },
{ word:"new", meaning:"ใหม่" },
{ word:"news", meaning:"ข่าว" },
{ word:"newspaper", meaning:"หนังสือพิมพ์" },
{ word:"next", meaning:"ถัดไป, ต่อไป" },
{ word:"next to", meaning:"ข้างๆ, ติดกับ" },
{ word:"nice", meaning:"ดี, ดีงาม" },
{ word:"night", meaning:"กลางคืน" },
{ word:"nine", meaning:"เก้า" },
{ word:"nineteen", meaning:"สิบเก้า" },
{ word:"ninety", meaning:"เก้าสิบ" },
{ word:"no", meaning:"ไม่" },
{ word:"no one", meaning:"ไม่มีใคร" },
{ word:"nobody", meaning:"ไม่มีใคร" },
{ word:"north", meaning:"ทิศเหนือ" },
{ word:"nose", meaning:"จมูก" },
{ word:"not", meaning:"ไม่" },
{ word:"note", meaning:"บันทึก, จดโน้ต" },
{ word:"nothing", meaning:"ไม่มีอะไรเลย" },
{ word:"November", meaning:"พฤศจิกายน" },
{ word:"now", meaning:"ตอนนี้" },
{ word:"number", meaning:"ตัวเลข, เบอร์" },
{ word:"nurse", meaning:"พยาบาล" },
{ word:"object", meaning:"วัตถุ, สิ่งของ" },
{ word:"o’clock", meaning:"นาฬิกา (บอกเวลาตรง)" },
{ word:"October", meaning:"ตุลาคม" },
{ word:"of", meaning:"ของ, เกี่ยวกับ" },
{ word:"off", meaning:"ปิด, พ้นไป" },
{ word:"office", meaning:"สำนักงาน" },
{ word:"often", meaning:"บ่อยๆ" },
{ word:"oh", meaning:"โอ้" },
{ word:"OK", meaning:"ตกลง, ใช้ได้" },
{ word:"old", meaning:"เก่า, แก่" },
{ word:"on", meaning:"บน" },
{ word:"once", meaning:"ครั้งหนึ่ง, เมื่อก่อน" },
{ word:"one", meaning:"หนึ่ง" },
{ word:"onion", meaning:"หัวหอม" },
{ word:"online", meaning:"ออนไลน์" },
{ word:"only", meaning:"เท่านั้น, เพียงแค่" },
{ word:"open", meaning:"เปิด" },
{ word:"opinion", meaning:"ความคิดเห็น" },
{ word:"opposite", meaning:"ตรงกันข้าม" },
{ word:"or", meaning:"หรือ" },
{ word:"orange", meaning:"ส้ม, สีส้ม" },
{ word:"order", meaning:"สั่งซื้อ, สั่ง" },
{ word:"other", meaning:"อื่น" },
{ word:"our", meaning:"ของพวกเรา" },
{ word:"out", meaning:"ข้างนอก, ออกไป" },
{ word:"outside", meaning:"ข้างนอก" },
{ word:"over", meaning:"เหนือ, เกิน, จบ" },
{ word:"own", meaning:"ของตัวเอง, เป็นเจ้าของ" },
{ word:"page", meaning:"หน้ากระดาษ" },
{ word:"paint", meaning:"ทาสี, วาดรูป" },
{ word:"painting", meaning:"ภาพวาด, การทาสี" },
{ word:"pair", meaning:"คู่" },
{ word:"paper", meaning:"กระดาษ" },
{ word:"paragraph", meaning:"ย่อหน้า" },
{ word:"parent", meaning:"ผู้ปกครอง, พ่อหรือแม่" },
{ word:"park", meaning:"สวนสาธารณะ, จอดรถ" },
{ word:"part", meaning:"ส่วน, ชิ้นส่วน" },
{ word:"partner", meaning:"หุ้นส่วน, คู่หู" },
{ word:"party", meaning:"งานเลี้ยง, พรรค" },
{ word:"passport", meaning:"หนังสือเดินทาง" },
{ word:"past", meaning:"อดีต, ผ่านมา" },
{ word:"pay", meaning:"จ่าย" },
{ word:"pen", meaning:"ปากกา" },
{ word:"pencil", meaning:"ดินสอ" },
{ word:"people", meaning:"ประชาชน, คน" },
{ word:"pepper", meaning:"พริกไทย, พริก" },
{ word:"perfect", meaning:"สมบูรณ์แบบ" },
{ word:"period", meaning:"ช่วงเวลา, ระยะเวลา" },
{ word:"person", meaning:"บุคคล, คน" },
{ word:"personal", meaning:"ส่วนบุคคล" },
{ word:"phone", meaning:"โทรศัพท์" },
{ word:"photo", meaning:"รูปถ่าย" },
{ word:"photograph", meaning:"ภาพถ่าย" },
{ word:"phrase", meaning:"วลี" },
{ word:"piano", meaning:"เปียโน" },
{ word:"picture", meaning:"รูปภาพ" },
{ word:"piece", meaning:"ชิ้น, อัน" },
{ word:"pig", meaning:"หมู" },
{ word:"pink", meaning:"สีชมพู" },
{ word:"place", meaning:"สถานที่" },
{ word:"plan", meaning:"แผนการ, วางแผน" },
{ word:"plane", meaning:"เครื่องบิน" },
{ word:"plant", meaning:"พืช, ปลูก" },
{ word:"play", meaning:"เล่น, บทละคร" },
{ word:"player", meaning:"ผู้เล่น" },
{ word:"please", meaning:"กรุณา, ได้โปรด" },
{ word:"point", meaning:"คะแนน, ชี้" },
{ word:"police", meaning:"ตำรวจ" },
{ word:"policeman", meaning:"ตำรวจชาย" },
{ word:"pool", meaning:"สระว่ายน้ำ" },
{ word:"poor", meaning:"ยากจน, น่าสงสาร" },
{ word:"popular", meaning:"เป็นที่นิยม" },
{ word:"positive", meaning:"เชิงบวก" },
{ word:"possible", meaning:"เป็นไปได้" },
{ word:"post", meaning:"โพสต์, ส่งไปรษณีย์" },
{ word:"potato", meaning:"มันฝรั่ง" },
{ word:"pound", meaning:"ปอนด์" },
{ word:"practice", meaning:"การฝึกซ้อม, ฝึกฝน" },
{ word:"practise", meaning:"ฝึกซ้อม" },
{ word:"prefer", meaning:"ชอบมากกว่า" },
{ word:"prepare", meaning:"เตรียมตัว" },
{ word:"present", meaning:"ปัจจุบัน, ของขวัญ" },
{ word:"pretty", meaning:"น่ารัก, ค่อนข้าง" },
{ word:"price", meaning:"ราคา" },
{ word:"probably", meaning:"อาจจะ" },
{ word:"problem", meaning:"ปัญหา" },
{ word:"product", meaning:"ผลิตภัณฑ์, สินค้า" },
{ word:"programme", meaning:"โปรแกรม, รายการ" },
{ word:"project", meaning:"โครงการ" },
{ word:"purple", meaning:"สีม่วง" },
{ word:"put", meaning:"วาง, ใส่" },
{ word:"quarter", meaning:"หนึ่งในสี่, 15 นาที" },
{ word:"question", meaning:"คำถาม" },
{ word:"quick", meaning:"รวดเร็ว" },
{ word:"quickly", meaning:"อย่างรวดเร็ว" },
{ word:"quiet", meaning:"เงียบ" },
{ word:"quite", meaning:"ค่อนข้าง" },
{ word:"radio", meaning:"วิทยุ" },
{ word:"rain", meaning:"ฝน, ฝนตก" },
{ word:"read", meaning:"อ่าน" },
{ word:"reader", meaning:"ผู้อ่าน" },
{ word:"reading", meaning:"การอ่าน" },
{ word:"ready", meaning:"พร้อม" },
{ word:"real", meaning:"จริง" },
{ word:"really", meaning:"จริงๆ" },
{ word:"reason", meaning:"เหตุผล" },
{ word:"red", meaning:"สีแดง" },
{ word:"relax", meaning:"ผ่อนคลาย" },
{ word:"remember", meaning:"จำได้" },
{ word:"repeat", meaning:"ทำซ้ำ, พูดซ้ำ" },
{ word:"report", meaning:"รายงาน" },
{ word:"restaurant", meaning:"ร้านอาหาร" },
{ word:"result", meaning:"ผลลัพธ์" },
{ word:"return", meaning:"กลับคืน" },
{ word:"rice", meaning:"ข้าว" },
{ word:"rich", meaning:"รวย" },
{ word:"ride", meaning:"ขี่" },
{ word:"right", meaning:"ขวา, ถูกต้อง" },
{ word:"river", meaning:"แม่น้ำ" },
{ word:"road", meaning:"ถนน" },
{ word:"room", meaning:"ห้อง, ที่ว่าง" },
{ word:"routine", meaning:"กิจวัตรประจำวัน" },
{ word:"rule", meaning:"กฎเกณฑ์, ข้อบังคับ" },
{ word:"run", meaning:"วิ่ง" },
{ word:"sad", meaning:"เศร้า" },
{ word:"salad", meaning:"สลัด" },
{ word:"salt", meaning:"เกลือ" },
{ word:"same", meaning:"เหมือนกัน" },
{ word:"sandwich", meaning:"แซนด์วิช" },
{ word:"Saturday", meaning:"วันเสาร์" },
{ word:"say", meaning:"พูด" },
{ word:"school", meaning:"โรงเรียน" },
{ word:"science", meaning:"วิทยาศาสตร์" },
{ word:"scientist", meaning:"นักวิทยาศาสตร์" },
{ word:"sea", meaning:"ทะเล" },
{ word:"second1", meaning:"ที่สอง" },
{ word:"number", meaning:"หมายเลข" },
{ word:"second1 (unit of time)", meaning:"วินาที" },
{ word:"section", meaning:"หมวดหมู่, ส่วน" },
{ word:"see", meaning:"เห็น, พบ" },
{ word:"sell", meaning:"ขาย" },
{ word:"send", meaning:"ส่ง" },
{ word:"sentence", meaning:"ประโยค" },
{ word:"September", meaning:"กันยายน" },
{ word:"seven", meaning:"เจ็ด" },
{ word:"seventeen", meaning:"สิบเจ็ด" },
{ word:"seventy", meaning:"เจ็ดสิบ" },
{ word:"share", meaning:"แบ่งปัน" },
{ word:"she", meaning:"เธอ (ผู้หญิง)" },
{ word:"sheep", meaning:"แกะ" },
{ word:"shirt", meaning:"เสื้อเชิ้ต" },
{ word:"shoe", meaning:"รองเท้า" },
{ word:"shop", meaning:"ร้านค้า" },
{ word:"shopping", meaning:"การซื้อของ" },
{ word:"short", meaning:"สั้น, เตี้ย" },
{ word:"should", meaning:"ควรจะ" },
{ word:"show", meaning:"แสดง, ให้ดู" },
{ word:"shower", meaning:"การอาบน้ำด้วยฝักบัว" },
{ word:"sick", meaning:"ป่วย" },
{ word:"similar", meaning:"คล้ายกัน" },
{ word:"sing", meaning:"ร้องเพลง" },
{ word:"singer", meaning:"นักร้อง" },
{ word:"sister", meaning:"พี่สาว, น้องสาว" },
{ word:"sit", meaning:"นั่ง" },
{ word:"situation", meaning:"สถานการณ์" },
{ word:"six", meaning:"หก" },
{ word:"sixteen", meaning:"สิบหก" },
{ word:"sixty", meaning:"หกสิบ" },
{ word:"skill", meaning:"ทักษะ" },
{ word:"skirt", meaning:"กระโปรง" },
{ word:"sleep", meaning:"นอนหลับ" },
{ word:"slow", meaning:"ช้า" },
{ word:"small", meaning:"เล็ก" },
{ word:"snake", meaning:"งู" },
{ word:"snow", meaning:"หิมะ" },
{ word:"so", meaning:"ดังนั้น, มาก" },
{ word:"some", meaning:"บางส่วน, บ้าง" },
{ word:"somebody", meaning:"บางคน" },
{ word:"someone", meaning:"บางคน" },
{ word:"something", meaning:"บางสิ่งบางอย่าง" },
{ word:"sometimes", meaning:"บางครั้ง" },
{ word:"son", meaning:"ลูกชาย" },
{ word:"song", meaning:"เพลง" },
{ word:"soon", meaning:"ในไม่ช้า" },
{ word:"sorry", meaning:"ขอโทษ, เสียใจ" },
{ word:"sound", meaning:"เสียง, ฟังดูเหมือน" },
{ word:"soup", meaning:"ซุป, น้ำแกง" },
{ word:"south", meaning:"ทิศใต้" },
{ word:"space", meaning:"พื้นที่, อวกาศ" },
{ word:"speak", meaning:"พูด" },
{ word:"special", meaning:"พิเศษ" },
{ word:"spell", meaning:"สะกดคำ" },
{ word:"spelling", meaning:"การสะกดคำ" },
{ word:"spend", meaning:"ใช้เงิน, ใช้เวลา" },
{ word:"sport", meaning:"กีฬา" },
{ word:"spring", meaning:"ฤดูใบไม้ผลิ" },
{ word:"stand", meaning:"ยืน" },
{ word:"star", meaning:"ดาว, ดารา" },
{ word:"start", meaning:"เริ่มต้น" },
{ word:"statement", meaning:"แถลงการณ์, ข้อความ" },
{ word:"station", meaning:"สถานี" },
{ word:"stay", meaning:"พักอยู่, อาศัย" },
{ word:"still", meaning:"ยังคง" },
{ word:"stop", meaning:"หยุด" },
{ word:"story", meaning:"เรื่องราว" },
{ word:"street", meaning:"ถนน" },
{ word:"strong", meaning:"แข็งแรง" },
{ word:"student", meaning:"นักเรียน" },
{ word:"study", meaning:"เรียน, ศึกษา" },
{ word:"style", meaning:"สไตล์, รูปแบบ" },
{ word:"subject", meaning:"วิชา, ประธาน" },
{ word:"success", meaning:"ความสำเร็จ" },
{ word:"sugar", meaning:"น้ำตาล" },
{ word:"summer", meaning:"ฤดูร้อน" },
{ word:"sun", meaning:"พระอาทิตย์" },
{ word:"Sunday", meaning:"วันอาทิตย์" },
{ word:"supermarket", meaning:"ซูเปอร์มาร์เก็ต" },
{ word:"sure", meaning:"มั่นใจ, แน่นอน" },
{ word:"sweater", meaning:"เสื้อกันหนาว" },
{ word:"swim", meaning:"ว่ายน้ำ" },
{ word:"swimming", meaning:"การว่ายน้ำ" },
{ word:"table", meaning:"โต๊ะ, ตาราง" },
{ word:"take", meaning:"เอาไป, พาไป" },
{ word:"talk", meaning:"พูดคุย" },
{ word:"tall", meaning:"สูง" },
{ word:"taxi", meaning:"แท็กซี่" },
{ word:"tea", meaning:"ชา" },
{ word:"teach", meaning:"สอน" },
{ word:"teacher", meaning:"ครู" },
{ word:"team", meaning:"ทีม" },
{ word:"teenager", meaning:"วัยรุ่น" },
{ word:"telephone", meaning:"โทรศัพท์" },
{ word:"television", meaning:"โทรทัศน์" },
{ word:"tell", meaning:"บอก" },
{ word:"ten", meaning:"สิบ" },
{ word:"tennis", meaning:"เทนนิส" },
{ word:"terrible", meaning:"แย่มาก, แย่ร้าย" },
{ word:"test", meaning:"แบบทดสอบ, ทดสอบ" },
{ word:"text", meaning:"ข้อความ" },
{ word:"than", meaning:"กว่า" },
{ word:"thank", meaning:"ขอบคุณ" },
{ word:"thanks", meaning:"ขอบใจ, ขอบคุณ" },
{ word:"that", meaning:"นั้น, สิ่งนั้น" },
{ word:"the", meaning:"คำนำหน้านามชี้เฉพาะ" },
{ word:"theatre", meaning:"โรงละคร" },
{ word:"their", meaning:"ของพวกเขา" },
{ word:"them", meaning:"พวกเขา (กรรม)" },
{ word:"then", meaning:"ตอนนั้น, ถัดจากนั้น" },
{ word:"there", meaning:"ที่นั่น" },
{ word:"they", meaning:"พวกเขา" },
{ word:"thing", meaning:"สิ่งของ, เรื่อง" },
{ word:"think", meaning:"คิด" },
{ word:"third", meaning:"ที่สาม" },
{ word:"thirsty", meaning:"กระหายน้ำ" },
{ word:"thirteen", meaning:"สิบสาม" },
{ word:"thirty", meaning:"สามสิบ" },
{ word:"this", meaning:"นี้, สิ่งนี้" },
{ word:"thousand", meaning:"พัน" },
{ word:"three", meaning:"สาม" },
{ word:"through", meaning:"ผ่าน, ทะลุ" },
{ word:"Thursday", meaning:"วันพฤหัสบดี" },
{ word:"ticket", meaning:"ตั๋ว" },
{ word:"time", meaning:"เวลา, ครั้ง" },
{ word:"tired", meaning:"เหนื่อย" },
{ word:"title", meaning:"ชื่อเรื่อง, ตำแหน่ง" },
{ word:"to", meaning:"ถึง, ไปยัง" },
{ word:"today", meaning:"วันนี้" },
{ word:"together", meaning:"ด้วยกัน" },
{ word:"toilet", meaning:"ห้องสุขา" },
{ word:"tomato", meaning:"มะเขือเทศ" },
{ word:"tomorrow", meaning:"พรุ่งนี้" },
{ word:"tonight", meaning:"คืนนี้" },
{ word:"too", meaning:"เกินไป, ด้วย" },
{ word:"tooth", meaning:"ฟัน" },
{ word:"topic", meaning:"หัวข้อ" },
{ word:"tourist", meaning:"นักท่องเที่ยว" },
{ word:"town", meaning:"เมือง" },
{ word:"traffic", meaning:"การจราจร" },
{ word:"train", meaning:"รถไฟ, ฝึกฝน" },
{ word:"travel", meaning:"ท่องเที่ยว" },
{ word:"tree", meaning:"ต้นไม้" },
{ word:"trip", meaning:"การเดินทาง" },
{ word:"trousers", meaning:"กางเกงขายาว" },
{ word:"true", meaning:"จริง, ถูกต้อง" },
{ word:"try", meaning:"พยายาม, ลอง" },
{ word:"T-shirt", meaning:"เสื้อยืด" },
{ word:"Tuesday", meaning:"วันอังคาร" },
{ word:"turn", meaning:"หมุน, เลี้ยว" },
{ word:"TV", meaning:"ทีวี" },
{ word:"twelve", meaning:"สิบสอง" },
{ word:"twenty", meaning:"ยี่สิบ" },
{ word:"twice", meaning:"สองครั้ง" },
{ word:"two", meaning:"สอง" },
{ word:"type", meaning:"ประเภท, พิมพ์" },
{ word:"umbrella", meaning:"ร่ม" },
{ word:"uncle", meaning:"ลุง, น้า, อาผู้ชาย" },
{ word:"under", meaning:"ใต้, ข้างใต้" },
{ word:"understand", meaning:"เข้าใจ" },
{ word:"university", meaning:"มหาวิทยาลัย" },
{ word:"until", meaning:"จนกระทั่ง" },
{ word:"up", meaning:"ขึ้น, ข้างบน" },
{ word:"upstairs", meaning:"ชั้นบน" },
{ word:"us", meaning:"พวกเรา (กรรม)" },
{ word:"use", meaning:"ใช้" },
{ word:"useful", meaning:"มีประโยชน์" },
{ word:"usually", meaning:"ตามปกติ, มักจะ" },
{ word:"vacation", meaning:"วันหยุดพักผ่อน" },
{ word:"vegetable", meaning:"ผัก" },
{ word:"very", meaning:"มาก" },
{ word:"video", meaning:"วิดีโอ" },
{ word:"village", meaning:"หมู่บ้าน" },
{ word:"visit", meaning:"เยี่ยมชม" },
{ word:"visitor", meaning:"ผู้มาเยือน" },
{ word:"wait", meaning:"รอ" },
{ word:"waiter", meaning:"บริกรชาย" },
{ word:"wake", meaning:"ตื่นนอน" },
{ word:"walk", meaning:"เดิน" },
{ word:"wall", meaning:"กำแพง, ผนัง" },
{ word:"want", meaning:"ต้องการ" },
{ word:"warm", meaning:"อบอุ่น" },
{ word:"wash", meaning:"ล้าง, ซัก" },
{ word:"watch", meaning:"ดู, นาฬิกาข้อมือ" },
{ word:"water", meaning:"น้ำ" },
{ word:"way", meaning:"ทาง, วิธี" },
{ word:"we", meaning:"พวกเรา" },
{ word:"wear", meaning:"สวมใส่" },
{ word:"weather", meaning:"สภาพอากาศ" },
{ word:"website", meaning:"เว็บไซต์" },
{ word:"Wednesday", meaning:"วันพุธ" },
{ word:"week", meaning:"สัปดาห์" },
{ word:"weekend", meaning:"วันหยุดสุดสัปดาห์" },
{ word:"welcome", meaning:"ยินดีต้อนรับ" },
{ word:"well", meaning:"ดี, บ่อน้ำ" },
{ word:"west", meaning:"ทิศตะวันตก" },
{ word:"what", meaning:"อะไร" },
{ word:"when", meaning:"เมื่อไหร่" },
{ where:"where", meaning:"ที่ไหน" },
{ word:"which", meaning:"อันไหน" },
{ word:"white", meaning:"สีขาว" },
{ word:"who", meaning:"ใคร" },
{ word:"why", meaning:"ทำไม" },
{ word:"wife", meaning:"ภรรยา" },
{ word:"will", meaning:"จะ, ความตั้งใจ" },
{ word:"win", meaning:"ชนะ" },
{ word:"window", meaning:"หน้าต่าง" },
{ word:"wine", meaning:"ไวน์" },
{ word:"winter", meaning:"ฤดูหนาว" },
{ word:"with", meaning:"กับ, ด้วย" },
{ word:"without", meaning:"โดยไม่มี" },
{ word:"woman", meaning:"ผู้หญิง" },
{ word:"wonderful", meaning:"มหัศจรรย์, ยอดเยี่ยม" },
{ word:"word", meaning:"คำศัพท์" },
{ word:"work", meaning:"ทำงาน, งาน" },
{ word:"worker", meaning:"คนงาน" },
{ word:"world", meaning:"โลก" },
{ word:"would", meaning:"จะ, ควรจะ" },
{ word:"write", meaning:"เขียน" },
{ word:"writer", meaning:"นักเขียน" },
{ word:"writing", meaning:"การเขียน" },
{ word:"wrong", meaning:"ผิด" },
{ word:"yeah", meaning:"ใช่" },
{ word:"year", meaning:"ปี" },
{ word:"yellow", meaning:"สีเหลือง" },
{ word:"yes", meaning:"ใช่" },
{ word:"yesterday", meaning:"เมื่อวานนี้" },
{ word:"you", meaning:"คุณ" },
{ word:"young", meaning:"วัยรุ่น, อายุน้อย" },
{ word:"your", meaning:"ของคุณ" },
{ word:"yourself", meaning:"ตัวคุณเอง" }
];